# Copyright 2024 CEI-UPM
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
# Daniel Vazquez (daniel.vazquez@upm.es)

CGRA:
  rows: 2
  columns: 2

  inputs:
    number: 2
    positions:  # Input number (<10!!) | Input cardinal position | PE number
      - 0N0
      - 1N1
  outputs:
    number: 2
    positions:  # Output number (<10!!) | Output cardinal position | PE number
      - 0S2
      - 1S3
