# Copyright 2024 CEI-UPM
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
# Daniel Vazquez (daniel.vazquez@upm.es)

CGRA:
  rows: 4
  columns: 4

  inputs:
    number: 4
    positions:  # Input number (<10!!) | Input cardinal position | PE number
      - 0N0
      - 1N1
      - 2N2
      - 3N3
  outputs:
    number: 4
    positions:  # Output number (<10!!) | Output cardinal position | PE number
      - 0S12
      - 1S13
      - 2S14
      - 3S15
